; 1. Round-Robin A Record untuk vault (IP obladi & desmond)
vault   IN      A       10.67.1.4         ; IP obladi
vault   IN      A       10.67.1.5         ; IP desmond

; 2. Round-Robin A Record untuk core (IP oblada & molly)
core    IN      A       10.67.1.6         ; IP oblada
core    IN      A       10.67.1.7         ; IP molly

; 3. CNAME Record
; INGAT: Beri tanda titik (.) di akhir FQDN tujuan CNAME
www     IN      CNAME   penny.k07.com.
static  IN      CNAME   abbey.k07.com.